from enum import Enum


class MatchReason(str, Enum):
    OK = "OK"

    BRAND_MISMATCH = "BRAND_MISMATCH"

    WEIGHT_MISMATCH = "WEIGHT_MISMATCH"

    FORM_MISMATCH = "FORM_MISMATCH"

    FLAVOUR_MISMATCH = "FLAVOUR_MISMATCH"

    NO_CANDIDATES = "NO_CANDIDATES"

    BELOW_THRESHOLD = "BELOW_THRESHOLD"