"""listing retailer product id and nullable product attrs

Revision ID: f2706c4097af
Revises: d58a16357da3
Create Date: 2026-09-23 05:21:12.319579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2706c4097af'
down_revision: Union[str, Sequence[str], None] = 'd58a16357da3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('retailer_product_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_listings_retailer_product_id'), 'listings', ['retailer_product_id'], unique=False)
    op.create_unique_constraint('uq_listings_store_retailer_product_id', 'listings', ['store_id', 'retailer_product_id'])
    op.alter_column('products', 'protein_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('products', 'flavour',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('products', 'weight',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               nullable=True)
    op.alter_column('products', 'weight_unit',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'weight_unit',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('products', 'weight',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               nullable=False)
    op.alter_column('products', 'flavour',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('products', 'protein_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_constraint('uq_listings_store_retailer_product_id', 'listings', type_='unique')
    op.drop_index(op.f('ix_listings_retailer_product_id'), table_name='listings')
    op.drop_column('listings', 'retailer_product_id')
    # ### end Alembic commands ###
